# Generated by Django 4.2.3 on 2023-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
