# Generated by Django 4.2.3 on 2023-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="avatar"
            ),
        ),
    ]
